"""fleet lifecycle dates and other equipment

Revision ID: 0002_fleet_lifecycle
Revises: 0001_baseline
Create Date: 2026-07-13 19:03:46.563888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_fleet_lifecycle'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('decommissioned_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquired_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('decommissioned_date', sa.Date(), nullable=True))

    # Rename (not add+drop) so existing purchase dates are preserved.
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.alter_column('purchase_date', new_column_name='acquired_date')
        batch_op.add_column(sa.Column('decommissioned_date', sa.Date(), nullable=True))

    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquired_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('decommissioned_date', sa.Date(), nullable=True))

    with op.batch_alter_table('docks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquired_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('decommissioned_date', sa.Date(), nullable=True))

    with op.batch_alter_table('sensor_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquired_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('decommissioned_date', sa.Date(), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decommissioned_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('decommissioned_date')

    with op.batch_alter_table('sensor_packages', schema=None) as batch_op:
        batch_op.drop_column('decommissioned_date')
        batch_op.drop_column('acquired_date')

    with op.batch_alter_table('docks', schema=None) as batch_op:
        batch_op.drop_column('decommissioned_date')
        batch_op.drop_column('acquired_date')

    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.drop_column('decommissioned_date')
        batch_op.drop_column('acquired_date')

    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.drop_column('decommissioned_date')
        batch_op.alter_column('acquired_date', new_column_name='purchase_date')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('decommissioned_date')
        batch_op.drop_column('acquired_date')

    op.drop_table('other_equipment')
    # ### end Alembic commands ###
